/* GENERATED by tools/package_arduino.py --sync from bindings/c/include/nobro_imu.h.
 * Do not edit here - edit the canonical header and re-run the sync. */
#ifndef NOBRO_IMU_H
#define NOBRO_IMU_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
#define NOBRO_IMU_API_VERSION 0x0100u
#define NOBRO_IMU_CALIBRATION_MAGIC 0x4D49u

typedef enum nobro_imu_family {
    NOBRO_IMU_UNKNOWN = 0,
    NOBRO_IMU_MPU6050 = 0x6050,
    NOBRO_IMU_MPU6500 = 0x6500,
    NOBRO_IMU_MPU9250 = 0x9250,
    NOBRO_IMU_MPU9255 = 0x9255,
    NOBRO_IMU_ICM45686 = 0x4568
} nobro_imu_family_t;

typedef enum nobro_imu_event {
    NOBRO_IMU_EVENT_NONE = 0,
    NOBRO_IMU_EVENT_SAMPLE = 1,
    NOBRO_IMU_EVENT_READ_ERROR = 2,
    NOBRO_IMU_EVENT_RECOVERED = 3,
    NOBRO_IMU_EVENT_RECOVERY_EXHAUSTED = 4,
    NOBRO_IMU_EVENT_CALIBRATION_REJECTED = 5
} nobro_imu_event_t;

typedef struct nobro_imu_sample {
    int32_t accel_mg[3];
    uint32_t accel_mag_mg;
    int32_t gyro_mdps[3];
    int32_t mag_milli_ut[3];
    int32_t temperature_centi_c;
    uint64_t timestamp_us;
} nobro_imu_sample_t;

typedef struct nobro_imu_calibration {
    int32_t accel_bias_mg[3];
    int32_t accel_scale_ppm[3];
    int32_t gyro_bias_mdps[3];
    int32_t mag_bias_milli_ut[3];
    int32_t mag_scale_ppm[3];
    uint16_t magic;
} nobro_imu_calibration_t;

typedef struct nobro_imu_identity {
    nobro_imu_family_t family;
    uint8_t who_am_i;
    uint8_t address;
    bool has_magnetometer;
} nobro_imu_identity_t;

typedef struct nobro_imu_diagnostics {
    uint32_t samples;
    uint32_t read_errors;
    uint32_t recoveries;
    uint16_t consecutive_errors;
    uint8_t recovery_attempts;
    nobro_imu_event_t last_event;
} nobro_imu_diagnostics_t;

#ifdef __cplusplus
}
#endif

#endif
