/* GENERATED by tools/package_arduino.py --sync from bindings/c/include/nobro_app.h.
 * Do not edit here - edit the canonical header and re-run the sync. */
/*
 * nobro_app.h - NobroRTOS C ABI for authoring a module in C.
 *
 * A C module implements the two callbacks (nobro_app_init / nobro_app_poll); the
 * NobroRTOS kernel admits it and drives them. The module reaches hardware and
 * publishes results only through the host services below - it never touches the
 * kernel internals. The ABI is plain extern "C", so a module compiled by any C
 * (or C++/Rust-extern-"C") toolchain links unchanged. See examples/imu_module.c.
 */
#ifndef NOBRO_APP_H
#define NOBRO_APP_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Host services (provided by NobroRTOS; call these from your module) ---- */

/* Monotonic microsecond timebase. */
uint64_t nobro_now_us(void);

/* I2C write of `len` bytes to `addr`. Returns 0 on success, <0 on bus error. */
int32_t nobro_i2c_write(uint8_t addr, const uint8_t *tx, uint32_t len);

/* I2C write-then-read (register read): write `tx_len` bytes, then read `rx_len`
 * bytes from `addr`. Returns 0 on success, <0 on bus error. */
int32_t nobro_i2c_write_read(uint8_t addr, const uint8_t *tx, uint32_t tx_len,
                             uint8_t *rx, uint32_t rx_len);

/* Publish a parsed IMU sample; the kernel computes magnitudes and fills the
 * host-readable report (so modules need no floating-point/math dependency). */
void nobro_publish_imu(uint8_t who, uint8_t dev_addr, int16_t ax, int16_t ay,
                       int16_t az, int16_t gx, int16_t gy, int16_t gz,
                       int16_t temp_raw);

/* ---- Declarative task graph (optional; allocation-free Tier-C facade) ---- */

typedef int32_t (*nobro_step_fn)(void);

typedef enum nobro_task_role {
    NOBRO_TASK_PERIODIC = 0,
    NOBRO_TASK_CONTROL = 1,
    NOBRO_TASK_SERVICE = 2,
} nobro_task_role_t;

typedef struct nobro_task_options {
    uint32_t role;
    uint32_t budget_us;   /* zero = role default */
    uint32_t deadline_us; /* zero = period */
    uint32_t jitter_us;   /* zero = role default */
    uint32_t blocking_us;
} nobro_task_options_t;

#define NOBRO_TASK_OPTIONS_INIT \
    { NOBRO_TASK_PERIODIC, 0u, 0u, 0u, 0u }

typedef enum nobro_result {
    NOBRO_OK = 0,
    NOBRO_ERR_STATE = -1,
    NOBRO_ERR_NAME = -2,
    NOBRO_ERR_PERIOD = -3,
    NOBRO_ERR_TASK_CAPACITY = -4,
    NOBRO_ERR_WIRE_CAPACITY = -5,
    NOBRO_ERR_ENDPOINT = -6,
    NOBRO_ERR_DUPLICATE_TASK = -7,
    NOBRO_ERR_OPTIONS = -8,
    NOBRO_ERR_ADMISSION = -9,
    NOBRO_ERR_STEP = -10,
} nobro_result_t;

/* Stable diagnostic identity and plain-sentence rendering for every result.
 * The negative ABI values remain unchanged; codes are shared with Rust,
 * C++11, Arduino, Python, JSON, and the generated public error index. */
static inline const char *nobro_app_error_code(int32_t status) {
    switch (status) {
    case NOBRO_ERR_STATE: return "NOBRO-E050";
    case NOBRO_ERR_NAME: return "NOBRO-E051";
    case NOBRO_ERR_PERIOD: return "NOBRO-E052";
    case NOBRO_ERR_TASK_CAPACITY: return "NOBRO-E053";
    case NOBRO_ERR_WIRE_CAPACITY: return "NOBRO-E054";
    case NOBRO_ERR_ENDPOINT: return "NOBRO-E055";
    case NOBRO_ERR_DUPLICATE_TASK: return "NOBRO-E056";
    case NOBRO_ERR_OPTIONS: return "NOBRO-E057";
    case NOBRO_ERR_ADMISSION: return "NOBRO-E058";
    case NOBRO_ERR_STEP: return "NOBRO-E059";
    default: return "";
    }
}

static inline const char *nobro_app_error_text(int32_t status) {
    switch (status) {
    case NOBRO_OK: return "Application graph is ready.";
    case NOBRO_ERR_STATE:
        return "Application graph state does not allow this operation.";
    case NOBRO_ERR_NAME: return "Names must use stable lowercase labels.";
    case NOBRO_ERR_PERIOD: return "Task rate and period must be valid.";
    case NOBRO_ERR_TASK_CAPACITY:
        return "Application task capacity is exceeded.";
    case NOBRO_ERR_WIRE_CAPACITY:
        return "Application wire capacity is exceeded.";
    case NOBRO_ERR_ENDPOINT: return "Wire endpoints must name existing tasks.";
    case NOBRO_ERR_DUPLICATE_TASK: return "Task name is already declared.";
    case NOBRO_ERR_OPTIONS:
        return "Task timing or resource options are invalid.";
    case NOBRO_ERR_ADMISSION: return "Application graph admission failed.";
    case NOBRO_ERR_STEP: return "Task callback failed.";
    default: return "Unknown application error.";
    }
}

/* Convert a frequency to a period. Literal zero is a compile-time error. */
#define NOBRO_HZ(rate) (1000000u / (uint32_t)(rate))
#ifndef HZ
#define HZ(rate) NOBRO_HZ(rate)
#endif

/* Names must be static lowercase labels (string literals are ideal). The
 * default role is a deadline-aware periodic driver. */
int32_t nobro_task(const char *name, uint32_t period_us, nobro_step_fn step);
int32_t nobro_task_with(const char *name, uint32_t period_us, nobro_step_fn step,
                        const nobro_task_options_t *options);

/* Declares a bounded graph/mailbox relationship. `capacity` is retained and
 * validated as declaration metadata; payload send/receive is a separate API. */
int32_t nobro_wire(const char *from, const char *to, uint32_t capacity);

/* Finalize through the shared Rust AppGraph validator, then dispatch due work. */
int32_t nobro_run(void);
int32_t nobro_poll(void);
uint32_t nobro_skipped_releases(void);
int32_t nobro_last_step_error(void);

/* ---- Module callbacks (you implement these; the kernel calls them) ---- */

/* Called once after admission, before polling. Return <0 to abort. */
int32_t nobro_app_init(void);

/* Called every cycle. Return <0 to signal a transient module error. */
int32_t nobro_app_poll(void);

#ifdef __cplusplus
}
#define NOBRO_EXTERN_C extern "C"
#else
#define NOBRO_EXTERN_C
#endif

/* Generate the two legacy Tier-C callbacks from one declarative setup function.
 * The setup function registers tasks/wires and returns nobro_run(). */
#define NOBRO_APP(configure_fn)                                     \
    NOBRO_EXTERN_C int32_t nobro_app_init(void) {                   \
        return (configure_fn)();                                    \
    }                                                               \
    NOBRO_EXTERN_C int32_t nobro_app_poll(void) {                   \
        return nobro_poll();                                        \
    }

#endif /* NOBRO_APP_H */
